# Generated by Django 5.2.11 on 2026-05-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0025_generatedwritingexercise_generatedwritingresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_id', models.CharField(max_length=100, unique=True)),
                ('super_category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('cefr', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('guideword', models.CharField(blank=True, max_length=300)),
                ('can_do', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('model_idx', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'rec_grammar',
                'ordering': ['cefr', 'super_category'],
            },
        ),
        migrations.CreateModel(
            name='ReadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_id', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('cefr', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('grade_level', models.FloatField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('text_length', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('model_idx', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'rec_reading',
                'ordering': ['cefr', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('topic', models.CharField(max_length=300)),
                ('cefr', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('written_task', models.TextField()),
                ('model_idx', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'rec_task',
                'ordering': ['cefr', 'level_number', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_id', models.CharField(max_length=100, unique=True)),
                ('headword', models.CharField(max_length=200)),
                ('pos', models.CharField(blank=True, max_length=50)),
                ('cefr', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('model_idx', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'rec_vocabulary',
                'ordering': ['cefr', 'headword'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('task', 'Task')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('was_clicked', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='users.learner')),
            ],
            options={
                'db_table': 'rec_log',
                'ordering': ['-recommended_at'],
                'indexes': [models.Index(fields=['learner', 'content_type'], name='rec_log_learner_591d16_idx')],
            },
        ),
    ]
