# Generated by Django 5.2.11 on 2026-05-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='synonyms',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
