# Generated by Django 5.2.11 on 2026-05-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_vocabularyitem_definition_vocabularyitem_example_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularyitem',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='synonym',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
