# Generated by Django 5.2.11 on 2026-05-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_remove_vocabularyitem_synonyms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyitem',
            name='synonym',
            field=models.TextField(blank=True),
        ),
    ]
