# Generated by Django 5.2.11 on 2026-03-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('learner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Avancé'), ('C1', 'C1 - Autonome'), ('C2', 'C2 - Maîtrise')], db_column='cefrlevel', default='A1', max_length=2)),
                ('progress', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'learner',
            },
        ),
    ]
