# Generated by Django 5.2.11 on 2026-03-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('is_valid', models.BooleanField(default=False)),
                ('coverage_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_text',
            },
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subunit',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'unit',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='learner',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Avancé'), ('C1', 'C1 - Autonome')], db_column='cefrlevel', default='A1', max_length=2),
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('true_false', 'True / False'), ('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.readingtext')),
            ],
            options={
                'db_table': 'reading_question',
            },
        ),
        migrations.AddField(
            model_name='readingtext',
            name='sub_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_texts', to='users.subunit'),
        ),
        migrations.AddField(
            model_name='subunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunits', to='users.unit'),
        ),
    ]
