# Generated by Django 5.2.11 on 2026-03-29 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_readingtext_subunit_unit_alter_learner_cefr_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField()),
                ('seuil_reussite', models.DecimalField(decimal_places=2, default=0.6, help_text='Score minimum pour valider ce niveau (ex: 0.60 = 60%)', max_digits=4)),
            ],
            options={
                'db_table': 'cefr_niveau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('score_final', models.DecimalField(blank=True, decimal_places=2, help_text='Score global en %', max_digits=5, null=True)),
                ('scores_par_niveau', models.JSONField(default=dict, help_text='Ex: {"A1": 100, "A2": 80, "B1": 60, "B2": 40, "C1": 20, "C2": 0}')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cefr_tests', to='users.learner')),
                ('niveau_final', models.ForeignKey(blank=True, help_text='Résultat calculé à la fin du test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_termines', to='users.niveau')),
            ],
            options={
                'db_table': 'cefr_test',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TestAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.CharField(help_text='Ex: spontaneous-speech-en-71660.mp3', max_length=255)),
                ('transcription', models.TextField(help_text="Texte transcrit de l'audio")),
                ('duree_secondes', models.PositiveIntegerField(blank=True, null=True)),
                ('sujet', models.CharField(blank=True, help_text='Ex: Sleep routine, Technology privacy...', max_length=200)),
                ('niveau_detecte', models.ForeignKey(blank=True, help_text='Peut être rempli manuellement ou automatiquement par cefr_detector.py', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_audios', to='users.niveau')),
            ],
            options={
                'db_table': 'cefr_test_audio',
                'ordering': ['niveau_detecte__ordre'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('grammar', 'Grammaire'), ('vocabulary', 'Vocabulaire'), ('listening', 'Listening')], help_text='grammar | vocabulary | listening', max_length=20)),
                ('type', models.CharField(choices=[('fill_blank', 'Compléter avec propositions (1 ou 2 trous)'), ('manual_input', 'Saisie manuelle'), ('mcq', 'QCM classique')], help_text='fill_blank | manual_input | mcq', max_length=20)),
                ('enonce', models.TextField(help_text='Phrase avec ___ pour les trous. Ex: He ___ the newspaper every day.')),
                ('reponse_attendue', models.TextField(help_text="Réponse correcte. Utiliser | comme séparateur :\n- 1 réponse       : 'reads'\n- 2 trous         : 'priest|professor'\n- synonymes       : 'information|data|info'\n- 2 bonnes rép.   : 'fake news|artificial intelligence'")),
                ('options', models.JSONField(blank=True, help_text="Propositions pour fill_blank et mcq. Ex: ['read','reads','readed','reading']", null=True)),
                ('ordre_dans_niveau', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage dans le niveau (1, 2, 3...)")),
                ('points', models.PositiveIntegerField(default=1)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.niveau')),
                ('audio', models.ForeignKey(blank=True, help_text='Uniquement pour les questions listening', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='users.testaudio')),
            ],
            options={
                'db_table': 'cefr_question',
                'ordering': ['niveau__ordre', 'categorie', 'ordre_dans_niveau'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reponse_donnee', models.TextField()),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.PositiveIntegerField(default=0)),
                ('temps_reponse_sec', models.PositiveIntegerField(blank=True, help_text='Temps pris pour répondre en secondes (optionnel)', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='users.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='users.test')),
            ],
            options={
                'db_table': 'cefr_reponse',
                'unique_together': {('test', 'question')},
            },
        ),
    ]
