# Generated by Django 5.2.11 on 2026-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_niveau_test_testaudio_question_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_ordre',
            field=models.JSONField(default=list, help_text='Liste ordonnée des UUIDs de questions pour ce test'),
        ),
    ]
