# Generated by Django 5.2.11 on 2026-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_test_questions_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
