# Generated by Django 5.2.11 on 2026-04-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_learner_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
