# Generated by Django 5.2.11 on 2026-04-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_learner_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerPreferences',
            fields=[
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to='users.learner')),
                ('reason', models.CharField(blank=True, choices=[('voyage', 'Travel'), ('travail', 'Work'), ('etudes', 'Studies'), ('culture', 'Culture'), ('communication', 'Communication'), ('Défi personnel', 'Personal challenge')], help_text="Pourquoi l'apprenant veut apprendre l'anglais", max_length=50)),
                ('interests', models.JSONField(default=list, help_text="Ex: ['voyage-tourisme', 'sport', 'business']")),
                ('other_interest', models.CharField(blank=True, help_text="Intérêt personnalisé saisi dans le champ 'Other'", max_length=200)),
                ('learning_style', models.CharField(blank=True, choices=[('video', 'Video'), ('texte', 'Text'), ('audio', 'Audio'), ('autre', 'Other')], help_text='Style préféré : video, texte, audio ou autre', max_length=20)),
                ('other_style', models.CharField(blank=True, help_text="Style personnalisé saisi dans le champ 'Other'", max_length=200)),
                ('daily_goal', models.CharField(blank=True, choices=[('5min', '5 min/day'), ('10min', '10 min/day'), ('15min', '15 min/day'), ('25min', '25 min/day')], help_text='Temps quotidien choisi : 5min, 10min, 15min ou 25min', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learner_preferences',
            },
        ),
    ]
