# Generated by Django 5.2.11 on 2026-04-05 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_learnerpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('correct_count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('results_json', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_exercise_results', to='users.learner')),
                ('reading_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.readingtext')),
            ],
            options={
                'db_table': 'reading_exercise_result',
                'unique_together': {('learner', 'reading_text')},
            },
        ),
    ]
