# Generated by Django 5.2.11 on 2026-04-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_readingexerciseresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_text', models.ForeignKey(help_text='Le texte ReadingText original qui a inspiré ce texte généré', on_delete=django.db.models.deletion.CASCADE, related_name='generated_texts', to='users.readingtext')),
                ('sub_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reading_texts', to='users.subunit')),
            ],
            options={
                'db_table': 'generated_reading_text',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('true_false', 'True / False'), ('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('generated_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.generatedreadingtext')),
            ],
            options={
                'db_table': 'generated_reading_question',
            },
        ),
    ]
