# Generated by Django 5.2.11 on 2026-04-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_generatedreadingtext_generatedreadingquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.JSONField(help_text="Réponses de l'apprenant: {question_id: 'réponse', ...}")),
                ('correct_count', models.IntegerField(help_text='Nombre de réponses correctes')),
                ('total_questions', models.IntegerField(help_text='Nombre total de questions')),
                ('score_percentage', models.IntegerField(help_text='Score en pourcentage (0-100)')),
                ('score_on_10', models.DecimalField(blank=True, decimal_places=1, help_text='Note sur 10 calculée automatiquement (ex: 7.5/10)', max_digits=3, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback in English encouraging more practice')),
                ('detailed_results_json', models.JSONField(default=list, help_text='Détail question par question avec comparaison')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('generated_text', models.ForeignKey(help_text="Le texte généré (GAI) que l'apprenant a pratiqué", on_delete=django.db.models.deletion.CASCADE, related_name='gen_results', to='users.generatedreadingtext')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_reading_exercise_results', to='users.learner')),
                ('original_text', models.ForeignKey(help_text='Le texte ORIGINAL qui a généré cet exercice', on_delete=django.db.models.deletion.CASCADE, related_name='gen_results_by_original', to='users.readingtext')),
            ],
            options={
                'db_table': 'generated_exercise_result',
            },
        ),
    ]
