# Generated by Django 5.2.11 on 2026-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_generatedexerciseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingexerciseresult',
            name='feedback',
            field=models.CharField(blank=True, help_text='Short feedback message in English (2-3 words)', max_length=50),
        ),
    ]
