# Generated by Django 5.2.11 on 2026-04-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_readingexerciseresult_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreadingtext',
            name='learner',
            field=models.ForeignKey(blank=True, help_text="L'apprenant qui a généré ce texte (null = anonyme)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reading_texts', to='users.learner'),
        ),
    ]
