# Generated by Django 5.2.11 on 2026-04-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_generatedreadingtext_learner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAudio',
            fields=[
                ('audio_id', models.CharField(help_text='Identifiant LJSpeech unique (ex: LJ020-0093)', max_length=20, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(help_text="Numéro d'unité pour référence rapide (ex: 01)", max_length=2)),
                ('unit_title', models.CharField(help_text="Titre de l'unité pédagogique", max_length=100)),
                ('subunit_key', models.CharField(help_text='Clé du sous-unité (ex: A1.1)', max_length=10)),
                ('subunit_title', models.CharField(help_text='Titre du sous-unité', max_length=100)),
                ('transcript', models.TextField(help_text="Transcription textuelle complète de l'audio")),
                ('audio_path', models.CharField(blank=True, help_text='Chemin vers le fichier audio', max_length=500)),
                ('cefr_level', models.CharField(help_text="Niveau CEFR de l'audio (A1, A2, B1, B2, C1)", max_length=2)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score de correspondance avec le sous-unité', max_digits=4, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text="Niveau de confiance de l'appariement", max_length=10)),
                ('vocab_score', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de vocabulaire correspondant au niveau CEFR (à remplir ultérieurement)', max_digits=5, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text="Durée de l'audio en secondes", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_unit', models.ForeignKey(help_text='Sous-unité pédagogique associée', on_delete=django.db.models.deletion.CASCADE, related_name='listening_audios', to='users.subunit')),
            ],
            options={
                'db_table': 'listening_audio',
                'ordering': ['unit_number', 'subunit_key'],
            },
        ),
        migrations.CreateModel(
            name='ListeningExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score en pourcentage (0-100)')),
                ('correct_count', models.IntegerField(help_text='Nombre de réponses correctes')),
                ('total', models.IntegerField(help_text='Nombre total de questions')),
                ('results_json', models.JSONField(help_text="Détail des réponses: {question_id: {'user_answer': '...', 'is_correct': True/False}, ...}")),
                ('feedback', models.CharField(blank=True, help_text='Feedback court en anglais (2-3 mots)', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.listeningaudio')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_exercise_results', to='users.learner')),
            ],
            options={
                'db_table': 'listening_exercise_result',
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_order', models.PositiveIntegerField(help_text="Ordre de la question dans l'audio (1-10)")),
                ('question_type', models.CharField(choices=[('true_false', 'True / False'), ('mcq', 'Multiple Choice Question'), ('word_order', 'Word Ordering'), ('fill_blank', 'Fill in the Blank'), ('synonym', 'Synonym'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary')], help_text='Type de question', max_length=20)),
                ('question_text', models.TextField(help_text='Texte de la question')),
                ('choices', models.JSONField(blank=True, help_text='Options pour MCQ/Fill_blank (format JSON)', null=True)),
                ('correct_answer', models.TextField(help_text='Réponse correcte')),
                ('target_word', models.CharField(blank=True, help_text='Mot cible (pour synonym/vocabulary)', max_length=50)),
                ('correct_order', models.JSONField(blank=True, help_text='Ordre correct des mots (pour word_order)', null=True)),
                ('explanation', models.TextField(blank=True, help_text='Explication de la réponse (optionnel)')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points attribués pour cette question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(help_text='Audio LJSpeech associé', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.listeningaudio')),
            ],
            options={
                'db_table': 'listening_question',
                'ordering': ['audio', 'question_order'],
            },
        ),
        migrations.AddIndex(
            model_name='listeningaudio',
            index=models.Index(fields=['unit_number'], name='listening_a_unit_nu_594cab_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningaudio',
            index=models.Index(fields=['cefr_level'], name='listening_a_cefr_le_00c75f_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningaudio',
            index=models.Index(fields=['subunit_key'], name='listening_a_subunit_453509_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listeningexerciseresult',
            unique_together={('learner', 'audio')},
        ),
        migrations.AddIndex(
            model_name='listeningquestion',
            index=models.Index(fields=['audio'], name='listening_q_audio_i_8de5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningquestion',
            index=models.Index(fields=['question_type'], name='listening_q_questio_001868_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listeningquestion',
            unique_together={('audio', 'question_order')},
        ),
    ]
