# Generated by Django 5.2.11 on 2026-04-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_listeningaudio_listeningexerciseresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingExercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction', models.TextField()),
                ('guiding_points', models.JSONField(default=list)),
                ('word_count_target', models.CharField(default='60-80 words', max_length=50)),
                ('model_answer_text', models.TextField()),
                ('model_answer_vocabulary', models.JSONField(default=list)),
                ('model_answer_grammar', models.JSONField(default=list)),
                ('key_vocabulary', models.JSONField(default=list)),
                ('grammar_patterns', models.JSONField(default=list, help_text='Patterns grammaticaux attendus')),
                ('forbidden_words', models.JSONField(default=list, help_text='Mots à éviter')),
                ('difficulty', models.CharField(default='A1', max_length=2)),
                ('theme', models.TextField(blank=True)),
                ('unit_title', models.CharField(blank=True, max_length=200)),
                ('subunit_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_exercises', to='users.subunit')),
            ],
            options={
                'db_table': 'writing_exercise',
                'ordering': ['sub_unit__unit__order', 'sub_unit__order'],
                'unique_together': {('sub_unit',)},
            },
        ),
        migrations.CreateModel(
            name='WritingExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_text', models.TextField()),
                ('word_count', models.IntegerField()),
                ('content_score', models.IntegerField(blank=True, help_text='Respect des consignes', null=True)),
                ('vocabulary_score', models.IntegerField(blank=True, null=True)),
                ('grammar_score', models.IntegerField(blank=True, null=True)),
                ('length_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('feedback_data', models.JSONField(default=dict, help_text="\n    {\n        'general': 'Feedback global',\n        'strengths': ['Point fort 1', 'Point fort 2'],\n        'improvements': ['À améliorer 1', 'À améliorer 2'],\n        'vocabulary_found': ['mot1', 'mot2'],\n        'vocabulary_missing': ['mot3', 'mot4'],\n        'grammar_errors': ['Erreur détectée'],\n        'word_count_feedback': 'Vous avez écrit X mots'\n    }\n    ")),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('evaluated', 'Évalué'), ('pending', 'En attente')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_exercise_results', to='users.learner')),
                ('writing_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.writingexercise')),
            ],
            options={
                'db_table': 'writing_exercise_result',
                'ordering': ['-submitted_at'],
                'unique_together': {('learner', 'writing_exercise')},
            },
        ),
    ]
