# Generated by Django 5.2.11 on 2026-04-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_writingexercise_writingexerciseresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingExercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(help_text='Thème de la sous-unité (ex: Morning Customs)', max_length=200)),
                ('level', models.CharField(default='A1', help_text='Niveau CEFR (A1, A2, …)', max_length=2)),
                ('instructions', models.TextField(default='Read the following sentence aloud. Practice your pronunciation.', help_text="Consigne affichée à l'apprenant")),
                ('sentence', models.TextField(help_text="Phrase que l'apprenant doit lire à voix haute")),
                ('sentence_words', models.JSONField(default=list, help_text='Liste ordonnée des mots de la phrase (générée automatiquement)')),
                ('vocabulary_categories', models.JSONField(default=list, help_text="Ex: ['time', 'verbs', 'home', 'feelings']")),
                ('audio_filename', models.CharField(help_text='Nom du fichier MP3 pré-généré. Ex: Unit01_A1.1_Morning_Customs.mp3 (stocké dans backend/data/speaking/audio_generated/)', max_length=255)),
                ('audio_path', models.CharField(blank=True, help_text="Chemin relatif complet vers l'audio de référence", max_length=500)),
                ('unit_number', models.CharField(help_text="Numéro d'unité pour référence rapide (ex: 01)", max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_unit', models.ForeignKey(help_text='Sous-unité pédagogique associée', on_delete=django.db.models.deletion.CASCADE, related_name='speaking_exercises', to='users.subunit')),
            ],
            options={
                'db_table': 'speaking_exercise',
                'ordering': ['unit_number', 'sub_unit__order'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_learner_path', models.CharField(blank=True, help_text="Chemin vers l'enregistrement vocal de l'apprenant (WebM/WAV)", max_length=500)),
                ('learner_transcript', models.TextField(blank=True, help_text="Texte transcrit automatiquement depuis l'enregistrement de l'apprenant")),
                ('word_results', models.JSONField(default=list, help_text='Comparaison mot à mot : liste de {word, status, said?}. status ∈ correct | wrong | missing | extra')),
                ('total_words', models.PositiveIntegerField(default=0, help_text='Nombre de mots dans la phrase de référence')),
                ('correct_words', models.PositiveIntegerField(default=0, help_text='Nombre de mots prononcés correctement')),
                ('accuracy_score', models.IntegerField(default=0, help_text='Score de précision en % (0-100)')),
                ('feedback', models.CharField(blank=True, choices=[('excellent', 'Excellent!'), ('very_good', 'Very good!'), ('good', 'Good job!'), ('keep_going', 'Keep going!'), ('try_again', 'Try again!')], help_text='Feedback court généré automatiquement selon le score', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Numéro de tentative pour cet exercice (1 = première fois)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(help_text="Apprenant ayant soumis l'exercice", on_delete=django.db.models.deletion.CASCADE, related_name='speaking_exercise_results', to='users.learner')),
                ('speaking_exercise', models.ForeignKey(help_text='Exercice de speaking concerné', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.speakingexercise')),
            ],
            options={
                'db_table': 'speaking_exercise_result',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='speakingexercise',
            index=models.Index(fields=['level'], name='speaking_ex_level_a578f0_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingexercise',
            index=models.Index(fields=['unit_number'], name='speaking_ex_unit_nu_b86b82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='speakingexercise',
            unique_together={('sub_unit',)},
        ),
        migrations.AddIndex(
            model_name='speakingexerciseresult',
            index=models.Index(fields=['learner', 'speaking_exercise'], name='speaking_ex_learner_11e6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingexerciseresult',
            index=models.Index(fields=['submitted_at'], name='speaking_ex_submitt_cd3808_idx'),
        ),
    ]
