# Generated by Django 5.2.11 on 2026-04-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_speakingexercise_speakingexerciseresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakingexercise',
            options={'ordering': ['sub_unit__unit__title', 'sub_unit__order']},
        ),
        migrations.RemoveIndex(
            model_name='speakingexercise',
            name='speaking_ex_unit_nu_b86b82_idx',
        ),
        migrations.RemoveField(
            model_name='speakingexercise',
            name='unit_number',
        ),
    ]
