# Generated by Django 5.2.11 on 2026-04-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_speakingexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speakingexerciseresult',
            unique_together={('learner', 'speaking_exercise')},
        ),
    ]
