# Generated by Django 5.2.11 on 2026-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_speakingexerciseresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingexerciseresult',
            name='feedback_data',
            field=models.JSONField(default=dict, help_text="\n    {\n        'general': 'Feedback global',\n        'strengths': ['Point fort 1', 'Point fort 2'],\n        'improvements': ['À améliorer 1', 'À améliorer 2'],\n        'vocabulary_found': ['mot1', 'mot2'],\n        'vocabulary_missing': ['mot3', 'mot4'],\n        'grammar_errors': ['Erreur détectée'],\n        'word_count_feedback': 'Vous avez écrit X mots',\n        'topic_relevance': 'Le texte est hors-sujet / sur le sujet'\n    }\n    "),
        ),
    ]
