# Generated by Django 5.2.11 on 2026-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_writingexerciseresult_feedback_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
