# Generated by Django 5.2.11 on 2026-04-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_learner_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='Ex: grammar_a1_sentence_construction', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=2)),
                ('category', models.CharField(blank=True, choices=[('phrases_noms_adjectifs', 'Phrases, noms, déterminants et adjectifs'), ('chiffres_nombres', 'Chiffres, nombres et quantités'), ('phrase_interrogative', 'La phrase interrogative'), ('difficultes', 'Quelques difficultés')], max_length=50)),
                ('order', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage dans le menu Grammar (L01=1, L02=2, …)")),
                ('is_active', models.BooleanField(default=True, help_text='False = cours masqué sur la plateforme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grammar_course',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Nombre de bonnes réponses')),
                ('total', models.IntegerField(help_text='Nombre total de questions')),
                ('results_json', models.JSONField(help_text='Détail par question : [{id, correct, given, correct_answer, explanation}, …]')),
                ('feedback', models.CharField(blank=True, choices=[('excellent', 'Excellent!'), ('good', 'Good job!'), ('needs_practice', 'Keep practicing!')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.grammarcourse')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_results', to='users.learner')),
            ],
            options={
                'db_table': 'grammar_exercise_result',
                'ordering': ['-submitted_at'],
                'unique_together': {('learner', 'course')},
            },
        ),
        migrations.CreateModel(
            name='GrammarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text="Identifiant dans le JSON : '1', '2', … '6'", max_length=10)),
                ('section_type', models.CharField(choices=[('lesson', 'Lesson'), ('tips', 'Tips / Common Mistakes'), ('exercise', 'Exercise')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le cours (= section_id converti en entier)")),
                ('content', models.JSONField(help_text='Contenu complet de la section stocké en jsonb PostgreSQL. lesson   → {explanation, formula, key_rules, examples, did_you_know, common_errors} tips     → {explanation, mistakes} exercise → {exercises, scoring}')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='users.grammarcourse')),
            ],
            options={
                'db_table': 'grammar_section',
                'ordering': ['order'],
                'unique_together': {('course', 'section_id')},
            },
        ),
    ]
