# Generated by Django 5.2.11 on 2026-04-26 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_grammarcourse_grammarexerciseresult_grammarsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTest',
            fields=[
                ('level', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField(default=15)),
                ('total_questions', models.PositiveIntegerField(default=20)),
                ('passing_score', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluation_test',
            },
        ),
        migrations.CreateModel(
            name='EvaluationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_attempts', to='users.learner')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.evaluationtest')),
            ],
            options={
                'db_table': 'evaluation_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('listening', 'Listening Comprehension'), ('reading', 'Reading Comprehension'), ('visual', 'Visual Comprehension'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary')], max_length=20)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True / False')], max_length=20)),
                ('question_text', models.TextField()),
                ('audio_path', models.CharField(blank=True, max_length=500)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('reading_text', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.evaluationtest')),
            ],
            options={
                'db_table': 'evaluation_question',
                'ordering': ['test', 'section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.evaluationattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.evaluationquestion')),
            ],
            options={
                'db_table': 'evaluation_answer',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
