# Generated by Django 5.2.11 on 2026-04-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_evaluationtest_evaluationattempt_evaluationquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSpeakingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text="Thème de la phrase générée (repris de l'exercice original)", max_length=200)),
                ('level', models.CharField(default='A1', help_text="Niveau CEFR (repris de l'exercice original)", max_length=2)),
                ('sentence', models.TextField(help_text="Phrase générée par l'IA que l'apprenant doit lire à voix haute")),
                ('sentence_words', models.JSONField(default=list, help_text='Liste ordonnée des mots de la phrase (générée automatiquement)')),
                ('instructions', models.TextField(default='Read the following sentence aloud. Practice your pronunciation.', help_text="Consigne affichée à l'apprenant")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(blank=True, help_text="L'apprenant qui a déclenché la génération", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_speaking_exercises', to='users.learner')),
                ('original_exercise', models.ForeignKey(help_text="L'exercice de speaking original qui a inspiré cette génération", on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to='users.speakingexercise')),
            ],
            options={
                'db_table': 'generated_speaking_exercise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedSpeakingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_transcript', models.TextField(blank=True, help_text="Texte transcrit automatiquement depuis l'enregistrement de l'apprenant")),
                ('word_results', models.JSONField(default=list, help_text='Comparaison mot à mot : liste de {word, status, said?}. status ∈ correct | wrong | missing | extra')),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('correct_words', models.PositiveIntegerField(default=0)),
                ('accuracy_score', models.IntegerField(default=0, help_text='Score de précision en % (0-100)')),
                ('feedback', models.CharField(blank=True, choices=[('excellent', 'Excellent!'), ('very_good', 'Very good!'), ('good', 'Good job!'), ('keep_going', 'Keep going!'), ('try_again', 'Try again!')], help_text='Feedback court généré automatiquement selon le score', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('generated_exercise', models.ForeignKey(help_text="L'exercice généré par IA concerné", on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.generatedspeakingexercise')),
                ('learner', models.ForeignKey(help_text="Apprenant ayant soumis l'exercice", on_delete=django.db.models.deletion.CASCADE, related_name='generated_speaking_results', to='users.learner')),
            ],
            options={
                'db_table': 'generated_speaking_result',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generatedspeakingexercise',
            index=models.Index(fields=['original_exercise'], name='generated_s_origina_01f63c_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedspeakingexercise',
            index=models.Index(fields=['learner'], name='generated_s_learner_7574f2_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedspeakingresult',
            index=models.Index(fields=['learner', 'generated_exercise'], name='generated_s_learner_62d582_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedspeakingresult',
            index=models.Index(fields=['submitted_at'], name='generated_s_submitt_8c1a5f_idx'),
        ),
    ]
