# Generated by Django 5.2.11 on 2026-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_generatedspeakingexercise_generatedspeakingresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedspeakingexercise',
            name='audio_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generatedspeakingexercise',
            name='audio_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
