# Generated by Django 5.2.11 on 2026-05-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_generatedspeakingexercise_audio_filename_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generatedspeakingexercise',
            unique_together={('original_exercise', 'learner')},
        ),
        migrations.CreateModel(
            name='GeneratedListeningExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text="Thème repris de l'audio original (subunit_title)", max_length=200)),
                ('cefr_level', models.CharField(default='A1', help_text="Niveau CEFR repris de l'audio original", max_length=2)),
                ('transcript', models.TextField(blank=True, help_text='Transcription générée par Ollama')),
                ('audio_filename', models.CharField(blank=True, max_length=255)),
                ('audio_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(blank=True, help_text="L'apprenant qui a déclenché la génération", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_listening_exercises', to='users.learner')),
                ('original_audio', models.ForeignKey(help_text="L'audio original qui a inspiré cette génération", on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to='users.listeningaudio')),
            ],
            options={
                'db_table': 'generated_listening_exercise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedListeningQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_order', models.PositiveIntegerField(help_text='Ordre 1-10')),
                ('question_type', models.CharField(choices=[('true_false', 'True / False'), ('mcq', 'Multiple Choice Question'), ('word_order', 'Word Ordering'), ('fill_blank', 'Fill in the Blank'), ('synonym', 'Synonym'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary')], max_length=20)),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('target_word', models.CharField(blank=True, max_length=50)),
                ('correct_order', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('generated_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.generatedlisteningexercise')),
            ],
            options={
                'db_table': 'generated_listening_question',
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedListeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score en % (0-100)')),
                ('correct_count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('results_json', models.JSONField(help_text='Détail par question : {q_id: {user_answer, correct_answer, is_correct, ...}}')),
                ('feedback', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('generated_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.generatedlisteningexercise')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_listening_results', to='users.learner')),
            ],
            options={
                'db_table': 'generated_listening_result',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generatedlisteningexercise',
            index=models.Index(fields=['original_audio'], name='generated_l_origina_f5f6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedlisteningexercise',
            index=models.Index(fields=['learner'], name='generated_l_learner_a815d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedlisteningexercise',
            unique_together={('original_audio', 'learner')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedlisteningquestion',
            unique_together={('generated_exercise', 'question_order')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedlisteningresult',
            unique_together={('learner', 'generated_exercise')},
        ),
    ]
