# Generated by Django 5.2.11 on 2026-05-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_generatedspeakingexercise_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedWritingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text="Thème repris de l'exercice original", max_length=200)),
                ('difficulty', models.CharField(default='A1', help_text="Niveau CEFR (repris de l'exercice original)", max_length=2)),
                ('instruction', models.TextField(blank=True, help_text="Nouvelle instruction générée par l'IA (même thème)")),
                ('guiding_points', models.JSONField(default=list, help_text="Points de guidage générés par l'IA")),
                ('word_count_target', models.CharField(default='60-80 words', max_length=50)),
                ('model_answer_text', models.TextField(blank=True, help_text="Paragraphe modèle généré par l'IA (60-80 mots)")),
                ('model_answer_vocabulary', models.JSONField(default=list)),
                ('model_answer_grammar', models.JSONField(default=list)),
                ('key_vocabulary', models.JSONField(default=list)),
                ('grammar_patterns', models.JSONField(default=list)),
                ('forbidden_words', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(blank=True, help_text="L'apprenant qui a déclenché la génération", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_writing_exercises', to='users.learner')),
                ('original_exercise', models.ForeignKey(help_text="L'exercice de writing original qui a inspiré cette génération", on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to='users.writingexercise')),
            ],
            options={
                'db_table': 'generated_writing_exercise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedWritingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_text', models.TextField()),
                ('word_count', models.IntegerField()),
                ('content_score', models.IntegerField(blank=True, null=True)),
                ('vocabulary_score', models.IntegerField(blank=True, null=True)),
                ('grammar_score', models.IntegerField(blank=True, null=True)),
                ('length_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('feedback_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('evaluated', 'Évalué'), ('pending', 'En attente')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_exercise', models.ForeignKey(help_text="L'exercice généré par IA que l'apprenant a complété", on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.generatedwritingexercise')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_writing_results', to='users.learner')),
            ],
            options={
                'db_table': 'generated_writing_result',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generatedwritingexercise',
            index=models.Index(fields=['original_exercise'], name='generated_w_origina_78599b_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedwritingexercise',
            index=models.Index(fields=['learner'], name='generated_w_learner_a3f9a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedwritingexercise',
            unique_together={('original_exercise', 'learner')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedwritingresult',
            unique_together={('learner', 'generated_exercise')},
        ),
    ]
